name: geoml
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - affine=2.2.2=py36_0
  - asn1crypto=0.24.0=py36_0
  - attrs=19.1.0=py36_1
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12=h8948797_3
  - cartopy=0.17.0=py36hbb7e04d_1
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h2e261b9_0
  - chardet=3.0.4=py36_1003
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py36_0
  - cryptography=2.7=py36h1ba5d50_0
  - curl=7.65.3=hbc83047_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fiona=1.8.4=py36hc38cc03_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - freexl=1.0.5=h14c3975_0
  - gdal=2.3.3=py36hbb2a789_0
  - geos=3.7.1=he6710b0_0
  - giflib=5.1.4=h14c3975_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py36_0
  - intel-openmp=2019.4=243
  - joblib=0.13.2=py36_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - kealib=1.4.7=hd0c454d_6
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.16.1=h173b8e3_7
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.65.3=h20c2e04_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=2.3.3=h2e7e64b_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.1=h11d0813_2
  - libpng=1.6.37=hbc83047_0
  - libpq=11.2=h20c2e04_0
  - libspatialite=4.3.0a=hb08deb6_19
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - lxml=4.4.1=py36hefd8a0e_0
  - matplotlib=3.1.0=py36h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py36h7b6447c_0
  - mkl_fft=1.0.14=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - munch=2.3.2=py36_0
  - ncurses=6.1=he6710b0_1
  - numpy-base=1.16.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1c=h7b6447c_1
  - owslib=0.18.0=py_0
  - pcre=8.43=he6710b0_0
  - pillow=6.1.0=py36h34e0f95_0
  - pip=19.2.2=py36_0
  - pixman=0.38.0=h7b6447c_0
  - poppler=0.65.0=h581218d_1
  - poppler-data=0.4.9=0
  - proj4=5.2.0=he6710b0_1
  - pycparser=2.19=py36_0
  - pyepsg=0.4.0=py36_0
  - pykdtree=1.3.1=py36hdd07704_2
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.2=py_0
  - pyproj=1.9.6=py36h14380d9_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py36_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.2=py_0
  - qt=5.9.7=h5867ecd_1
  - rasterio=1.0.21=py36hc38cc03_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py36_0
  - scikit-learn=0.21.2=py36hd81dba3_0
  - scipy=1.3.1=py36h7c811a0_0
  - shapely=1.6.4=py36h86c5351_0
  - sip=4.19.8=py36hf484d3e_0
  - snuggs=1.4.6=py_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py36h7b6447c_0
  - urllib3=1.24.2=py36_0
  - xerces-c=3.2.2=h780794e_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.8.0
    - astor==0.8.0
    - backcall==0.1.0
    - bleach==3.1.0
    - blosc==1.8.1
    - branca==0.3.1
    - cachetools==3.1.1
    - click==7.0
    - cloudpickle==0.4.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - descarteslabs==0.25.0
    - entrypoints==0.3
    - gast==0.2.2
    - geojson==2.5.0
    - google-pasta==0.1.7
    - grpcio==1.23.0
    - ipykernel==5.1.2
    - ipyleaflet==0.11.1
    - ipython==7.7.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.1
    - jinja2==2.10.1
    - jsonschema==3.0.2
    - jupyter-client==5.3.1
    - jupyter-core==4.5.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - mercantile==1.1.2
    - mistune==0.8.4
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - notebook==6.0.1
    - numpy==1.17.1
    - pandas==0.25.1
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - protobuf==3.9.1
    - ptyprocess==0.6.0
    - pyarrow==0.13.0
    - pygments==2.4.2
    - pyrsistent==0.15.4
    - pyzmq==18.1.0
    - send2trash==1.5.0
    - setuptools==41.2.0
    - six==1.12.0
    - tensorboard==1.14.0
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.2
    - traitlets==4.3.2
    - traittypes==0.2.1
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.15.5
    - wheel==0.33.6
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - xarray==0.12.3
prefix: /home/Peter.Kerins/anaconda3/envs/geoml

